<h1 class="center">Admin Login</h1>
<div class="row-fluid">
	<form class="span4 offset4" method="POST" action="/admin/login.authenticate">
		<?php
		if (isset($_SESSION['__notification']))
		{
			?>
			<div class="alert alert-error">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<?php echo $_SESSION['__notification']; ?>
			</div>
			<?php
			unset($_SESSION['__notification']);
		}
		?>
		<fieldset>
			<label for="username">Username</label>
			<input type="text" name="username" class="span12">
			<label for="password">Password</label>
			<input type="password" name="password" class="span12">
			<button type="submit" class="btn btn-primary pull-right">Login</button>
		</fieldset>
	</form>
</div>
